k9s:
  cluster: arn:aws:eks:us-east-1:310089926162:cluster/dev-stable-eks
  namespace:
    active: kube-system
    lockFavorites: false
    favorites:
    - kube-system
    - stable-sand
    - default
  view:
    active: ctx
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
