k9s:
  cluster: arn:aws:eks:us-east-1:765948876311:cluster/stag-stable-eks
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - external-secrets
    - stable-sand
    - stable
    - kube-system
    - default
  view:
    active: ctx
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
