k9s:
  cluster: arn:aws:eks:us-east-1:765948876311:cluster/stag-stable-eks
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
    - stable
  view:
    active: ctx
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
