k9s:
  cluster: arn:aws:eks:us-east-1:398986686239:cluster/central-stable-eks
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
