k9s:
  cluster: arn:aws:eks:us-east-1:028201126485:cluster/prod-stable-eks
  namespace:
    active: external-secrets
    lockFavorites: false
    favorites:
    - external-secrets
    - kube-system
    - stable-sand
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
