k9s:
  cluster: shared-sandbox/cird60pd0i29tod5ejag
  namespace:
    active: proxysql
    lockFavorites: false
    favorites:
      - proxysql
      - default
  view:
    active: ns
  featureGates:
    nodeShell: false
  proxy: null
