k9s:
  cluster: arn:aws:eks:us-east-1:016004081735:cluster/prod-market-eks
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
