k9s:
  cluster: arn:aws:eks:us-east-1:310089926162:cluster/dev-stable-eks
  namespace:
    active: stable-sand
    lockFavorites: false
    favorites:
    - stable-sand
    - stable
    - all
    - default
  view:
    active: ns
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
